exclude = ["backup_archive", "backup_ui", "backup_ui_qt", "CHANGELOG.md", "DEV_PLAN.md"]

[lint]
select = ["E", "F", "W", "I", "B", "SIM", "C"]
ignore = []

[lint.pycodestyle]
max-line-length = 120

[lint.per-file-ignores]
"tools/*" = ["F821", "E402", "B904"]
"ui/main_window.py" = ["F401", "F811", "E402", "B904"]
"simulation/workflow_simulation.py" = ["E402"]
"agents/self_regeneration_manager.py" = ["E501", "F541", "W293", "E302", "E305"]
"agents/enhanced_memory_manager.py" = ["E501", "E402", "F541", "E302", "E305"]
"ui/tools/tool_manager_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/memory/memory_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/intelligence/context_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/intelligence/decision_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/intelligence/intelligence_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/layout/dynamic_ui_manager.py" = ["E501", "E402", "E302", "E305"]
"ui/layout/theme_manager.py" = ["E501", "E402", "E302", "E305"]
"ui/layout/theme_ui.py" = ["E501", "E402", "E302", "E305"]
"ui/main_ui.py" = ["E501", "E402", "E302", "E305"]
"tests/plugin_marketplace_test.py" = ["E402"]
"tests/test_enhanced_memory_manager_fix.py" = ["E402"]
