[tool.ruff]
# Вказуємо цільову версію Python
# Замініть на вашу версію, наприклад py39
target-version = "py39"

# Шляхи до коду для аналізу
src = ["."]

# Виключення непотрібних директорій
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "backup_archive",
    "backup_ui",
    "backup_ui_qt",
]

line-length = 120

[tool.ruff.lint]
select = ["E", "F", "B", "SIM", "I"]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.bandit]
# Configuration for bandit security linter
exclude_dirs = ["backup_archive", "backup_ui", "backup_ui_qt", "tests", ".venv"]
skips = ["B101", "B601", "B602", "B603"]  # Skip assert statements and subprocess calls in testing

[tool.bandit.assert_used]
skips = ["*_test.py", "*/test_*.py", "**/tests/**"]

[tool.pytest.ini_options]
# Pytest configuration
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short --strict-markers"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

[tool.coverage.run]
source = ["."]
omit = [
    "backup_archive/*",
    "backup_ui/*", 
    "backup_ui_qt/*",
    "tests/*",
    ".venv/*",
    "*/site-packages/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
