name: Atlas CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      run: ruff check .

    - name: Type check with mypy
      # Ignoring missing imports for now as some dependencies might be tricky on CI
      run: mypy . --ignore-missing-imports

    - name: Run tests
      run: python -m unittest discover tests
